force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Jogador participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Jogador__c/fields/DataMorte__c.field-meta.xml
<CustomField>
    <fullName>DataMorte__c</fullName>
    <description>Usado para informar a data da morte</description>
    <inlineHelpText>Data da Morte</inlineHelpText>
    <label>Data da Morte</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Usado para informar se o jogador foi eliminado</description>
    <inlineHelpText>Jogador eliminado?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/JogadoresTriggerHandler.cls
public without sharing class JogadoresTriggerHandler {
  
  public static void beforeUpdate(List<Jogador__c> records, Map<Id, Jogador__c> oldMap) {
    for (Jogador__c jogador : records) {
      beforeUpdate(jogador, oldMap.get(jogador.Id));
    }

  }

  private static beforeUpdate(Jogador__c record, JOgador__c recordOld) {
    if (!jogadorOld.Eliminado__c && jogador.Eliminado__c) {
      jogador.DataMorte__c = System.now();
    }

  }
}